Repository puppetlabs/puppet-vscode, pull requests merged in 2018-10, with the labels that each got.

#394 (maint) Convert FormatDocumentProvider to async function
  src/feature/FormatDocumentFeature.ts
Labels: maintenance

#395 (GH-337) Update vscode-languageclient and vscode modules
  package-lock.json
  package.json
  src/PuppetLanguageClient.ts
Labels: maintenance

#396 (GH-334) Update vscode-extension-telemetry
  package.json
Labels: feature

#393 (GH-399) Update status bar loading UI
  src/PuppetLanguageClient.ts
  src/PuppetStatusBar.ts
  src/connection.ts
  src/feature/FormatDocumentFeature.ts
  src/feature/NodeGraphFeature.ts
  src/feature/PuppetResourceFeature.ts
  src/interfaces.ts
Labels: feature

#401 (GH-400) Fix Path environment parsing for Ruby Helper
  src/rubyHelper.ts
Labels: bug

#372 (GH-397) Use the Language Server with sidecar (0.15.0
  CHANGELOG.md
  editor-services.json
  gulpfile.js
Labels: feature

#402 (maint) Document 0.13 Release
  CHANGELOG.md
  README.md
  docs/assets/breadcrumbs.gif
  docs/assets/go_to_symbol.gif
  docs/assets/loading_status.gif
  docs/assets/outline_view.gif
Labels: documentation

#407 (GH-405) Update README and links into the README
  .github/ISSUE_TEMPLATE/issue_template.md
  README.md
Labels: bug

#414 (GH-411) Remove class name for symbols from README
  README.md
Labels: documentation
