Repository puppetlabs/puppet-vscode, pull requests merged in 2018-12, with the labels that each got.

#437 (release) 0.14.0
  .vscodeignore
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#425 (GH-412) Implement ConnectionHandler
  .vscode/settings.json
  package-lock.json
  package.json
  src/PuppetLanguageClient.ts
  src/connection.ts
  src/debugAdapter.ts
  src/extension.ts
  src/feature/FormatDocumentFeature.ts
  src/feature/NodeGraphFeature.ts
  src/feature/PuppetResourceFeature.ts
  src/handler.ts
  src/handlers/stdio.ts
  src/handlers/tcp.ts
  src/helpers/commandHelper.ts
  src/interfaces.ts
  src/logging/outputchannel.ts
  src/rubyHelper.ts
  src/settings.ts
Labels: feature

#444 (GH-439) Remove RestartSession Command
  README.md
  docs/assets/reload_language_server.gif
  package.json
  src/PuppetStatusBar.ts
  src/extension.ts
  src/messages.ts
Labels: feature

#442 (GH-335) Add option to disable language server
  src/extension.ts
Labels: feature

#443 (doc) Update puppet.installDirectory usage
  README.md
Labels: documentation

#441 (GH-447)(GH-440)(GH-446) Add modulepath setting and deprecate enable-file-cache
  CHANGELOG.md
  editor-services.json
  package.json
  src/configuration.ts
  src/helpers/commandHelper.ts
  src/interfaces.ts
  src/settings.ts
Labels: extension, feature, lang-server
