Repository puppetlabs/puppet-vscode, pull requests merged in 2019-05, with the labels that each got.

#511 (GH-509) Update node dependencies
  package-lock.json
  package.json
Labels: extension

#512 (GH-499) Setting to Disable Editor Services
  package.json
Labels: bug, extension

#510 (GH-505) PDK New Module Button Visibility Setting
  package.json
Labels: extension, feature

#503 (GH-502) change the default install type to PDK
  package.json
  src/settings.ts
  src/test/configuration.test.ts
Labels: extension

#518 (maint) Update Travis urls
  README.md
  package.json
Labels: maintenance

#517 (maint) Update recommended tslint extension
  .vscode/extensions.json
Labels: maintenance

#519 (GH-507)(GH-508) Document Puppet Version Support
  README.md
Labels: documentation
