Repository puppetlabs/puppet-vscode, pull requests merged in 2019-01, with the labels that each got.

#457 (Maint) Update vendoring for Editor Syntax
  README_BUILD.md
  editor-components.json
  editor-services.json
  gulpfile.js
  syntaxes/.gitignore
  syntaxes/puppet.tmLanguage
Labels: extension, feature, syntax-highlighting

#458 (GH-295)(GH-288) Add puppetfile support
  languages/puppetfile-language-configuration.json
  package.json
  snippets/puppetfile.snippets.json
  src/PuppetStatusBar.ts
  src/extension.ts
  src/handler.ts
  syntaxes/puppetfile.cson.json
Labels: extension

#462 (GH-453) Expose advanced additional Editor Service Settings
  package.json
  src/handlers/stdio.ts
  src/handlers/tcp.ts
  src/helpers/commandHelper.ts
  src/settings.ts
Labels: extension, feature

#463 (GH-288) Change puppetfile snippets to single line
  snippets/puppetfile.snippets.json
Labels: extension, feature

#450 (GH-375) Implement Docker connection handler
  README.md
  package.json
  src/extension.ts
  src/handler.ts
  src/handlers/docker.ts
  src/helpers/commandHelper.ts
  src/interfaces.ts
  src/settings.ts
Labels: feature

#448 (GH-459) Use New debug adapter API
  package.json
  src/configuration.ts
  src/debugAdapter.ts
  src/extension.ts
  src/feature/DebugConfigurationFeature.ts
  src/feature/DebuggingFeature.ts
  src/handlers/stdio.ts
  src/handlers/tcp.ts
  src/helpers/commandHelper.ts
  src/interfaces.ts
  src/rubyHelper.ts
Labels: extension

#468 (maint) Update telemetry
  package-lock.json
  package.json
  src/extension.ts
Labels: feature

#470 (GH-469) Restore puppet palatte commands
  package.json
Labels: bug

#473 (release) 0.16.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
