Repository puppetlabs/puppet-vscode, pull requests merged in 2020-01, with the labels that each got.

#602 (GH-289) Auto Indent for Types with Titles
  languages/puppet-language-configuration.json
  languages/puppetfile-language-configuration.json
  src/extension.ts
Labels: feature

#604 (maint) Remove Language Configuration JSON entries
  package.json
Labels: bug, maintenance

#606 (GH-605) Use correct setting name for module path
  src/helpers/commandHelper.ts
Labels: bug

#607 (maint) Release 0.23.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#609 (maint) Update README with Documentation Website links
  README.md
Labels: maintenance
