Repository puppetlabs/puppet-vscode, pull requests merged in 2020-05, with the labels that each got.

#637 (maint) Update telemetry for facts
  CHANGELOG.md
  src/views/facts.ts
Labels: maintenance

#648 (GH-647) Puppet Facts Welcome View
  CHANGELOG.md
  package.json
Labels: feature

#651 (maint) Update release process
  tools/RELEASE.md
Labels: documentation, maintenance

#641 (GH-583) Change build script githubref and optimize build times
  CHANGELOG.md
  package.json
  psakefile.ps1
Labels: maintenance

#654 (GH-652) Update Extension Install gif
  README.md
Labels: documentation

#655 (maint) Automate Publishing VS Code Extension
  .github/workflows/release.yml
Labels: maintenance

#656 (maint) Fix Facts View typo
  package.json
Labels: maintenance

#657 (maint) Release 0.26.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#660 (GH-649) Reduce Activation Events
  CHANGELOG.md
  package.json
Labels: extension

#659 (GH-639) Deprecate Bolt commands
  CHANGELOG.md
  src/feature/BoltFeature.ts
Labels: feature

#658 (maint) Fix Automatic Github Release
  .github/workflows/release.yml
Labels: maintenance

#661 (GH-643) Enable and Configure prettier
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  CHANGELOG.md
  assets/js/main.js
  package.json
  snippets/puppetfile.snippets.json
  src/configuration.ts
  src/configuration/pathResolver.ts
  src/configuration/pdkResolver.ts
  src/extension.ts
  src/feature.ts
  src/feature/BoltFeature.ts
  src/feature/DebuggingFeature.ts
  src/feature/FormatDocumentFeature.ts
  src/feature/PDKFeature.ts
  src/feature/PuppetModuleHoverFeature.ts
  src/feature/PuppetNodeGraphFeature.ts
  src/feature/PuppetResourceFeature.ts
  src/feature/PuppetStatusBarFeature.ts
  src/feature/UpdateConfigurationFeature.ts
  src/handler.ts
  src/handlers/stdio.ts
  src/handlers/tcp.ts
  src/helpers/commandHelper.ts
  src/interfaces.ts
  src/logging.ts
  src/logging/outputchannel.ts
  src/messages.ts
  src/settings.ts
  src/telemetry.ts
  src/test/suite/configuration.test.ts
  src/test/suite/extension.test.ts
  src/test/suite/index.ts
  src/test/suite/paths.test.ts
  src/test/suite/pdkResolver.test.ts
  src/views/facts.ts
  tsconfig.json
  tslint.json
Labels: maintenance

#665 (GH-646) Remove all documentation gifs
  docs/assets/auto_complete.gif
  docs/assets/bolt_config_command.gif
  docs/assets/bolt_inventory_command.gif
  docs/assets/breadcrumbs.gif
  docs/assets/change-puppet-version.gif
  docs/assets/extension_install.gif
  docs/assets/go_to_symbol.gif
  docs/assets/hover_support.gif
  docs/assets/language_server.gif
  docs/assets/loading_status.gif
  docs/assets/outline_view.gif
  docs/assets/pdk_new_class.gif
  docs/assets/pdk_new_module.gif
  docs/assets/pdk_test_unit.gif
  docs/assets/pdk_validate.gif
  docs/assets/puppet_debug.gif
  docs/assets/puppet_node_graph.gif
  docs/assets/puppet_resource.gif
  docs/assets/syntax_highlighting.png
Labels: maintenance

#662 (GH-642) Migrate to ES Lint
  .eslintignore
  .eslintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/configuration.ts
  src/configuration/pathResolver.ts
  src/configuration/pdkResolver.ts
  src/extension.ts
  src/feature/BoltFeature.ts
  src/feature/DebuggingFeature.ts
  src/feature/FormatDocumentFeature.ts
  src/feature/PDKFeature.ts
  src/feature/PuppetModuleHoverFeature.ts
  src/feature/PuppetNodeGraphFeature.ts
  src/feature/PuppetResourceFeature.ts
  src/feature/PuppetStatusBarFeature.ts
  src/feature/UpdateConfigurationFeature.ts
  src/handler.ts
  src/handlers/stdio.ts
  src/handlers/tcp.ts
  src/helpers/commandHelper.ts
  src/logging/file.ts
  src/logging/null.ts
  src/logging/outputchannel.ts
  src/logging/stdout.ts
  src/messages.ts
  src/settings.ts
  src/telemetry.ts
  src/views/facts.ts
  tslint.json
Labels: maintenance
